### ISSUE TITLE
Does login work ?

### ISSUE THREAD

**Issue by madshansens** [mgp25/TikTok#1]
Hi, thanks for your contribution to the community. 

Is it possible to login now with the tool or not ? Does the api generate X-Gorgon and X-Khronos on it's own or do we have to import it in some way ?

Sorry for asking noob questions, looking forward to your work and i will contribute to this project in the future..

**Comment by mgp25** [comment]
Hello @madshansens,

The login function is correct and it is working fine however gorgon token is required. Right now it is only available for researchers and upon request, once the full API is published I will think wether to publish them in the public or not.

Best regards

**Comment by fhartavi** [comment]
Hello,
I think you must share because of we can develop more secured applications to reverse engineering.
Thanks

**Comment by Logxn** [comment]
@fhartavi 

He mustn't do anything.
As he deleted my issue to this specific topic and only read my mail and didn't care to reply, I highly assume that he won't publish how the header is produced.

While I do get a few reasons, I also dislike the decision.
